"""Backward-compatibility stub — file moved to cad/legacy/parts/side_panels.py."""
from cad.legacy.parts.side_panels import (  # noqa: F401
    _cut_side_panel_vents as make_side_panel_vents,
    _make_side_panel_frame as make_side_panel_frame,
    _make_side_panel_mounts as make_side_panel_mounts,
    _make_side_panel_ribs as make_side_panel_ribs,
    create_left_side_panel,
    create_left_side_panel_lower,
    create_left_side_panel_middle,
    create_left_side_panel_upper,
    create_right_side_panel,
    create_right_side_panel_lower,
    create_right_side_panel_middle,
    create_right_side_panel_upper,
    create_side_panel,
    make_side_panel_mount_rail,
    make_side_panel_mount_rail_lower,
    make_side_panel_mount_rail_middle,
    make_side_panel_mount_rail_upper,
    make_side_panel_tile,
    side_panel_length,
    side_panel_mount_y_positions,
    side_panel_mount_z_positions,
    side_panel_tile_center_z,
    side_panel_tile_height,
)
