"""Parametric dimensions for Homelab Modular Tower.

All dimensions are in millimetres. STEP/STL files are derived from these
CadQuery parameters and are not the source of truth.
"""

PROJECT_NAME = "Homelab Modular Tower v1"
CURRENT_REVISION = "mk0.3"

# Global dimensions
TOWER_WIDTH = 190.0
TOWER_DEPTH = 190.0
OUTER_WIDTH = 190.0
OUTER_DEPTH = 190.0
UNIT_HEIGHT = 35.0
TOTAL_UNITS = 8.5
TOWER_HEIGHT = TOTAL_UNITS * UNIT_HEIGHT + 24.0

# Material and print clearances
WALL_THICKNESS = 3.0
RIB_THICKNESS = 4.0
MIN_PRINTABLE_FEATURE = 1.2
FILLET_RADIUS = 0.8
PLACEHOLDER_CHAMFER = 0.8

# Rods and fasteners
ROD_DIAMETER = 5.0
ROD_CLEARANCE = 5.6
ROD_CENTER_OFFSET = 12.0
ROD_OFFSET = ROD_CENTER_OFFSET
ROD_LENGTH = TOWER_HEIGHT
M5_WASHER_DIAMETER = 12.0
M5_WASHER_SEAT_DEPTH = 1.8
M5_NUT_SIDES = 6
M5_NUT_FLAT_DIAMETER = 9.4
M5_NUT_SEAT_DEPTH = 4.2
M3_CLEARANCE = 3.4
M4_CLEARANCE = 4.4
SCREW_CLEARANCE_M3 = M3_CLEARANCE
SCREW_CLEARANCE_M5 = ROD_CLEARANCE
HEAT_SET_INSERT_M3_DIAMETER = 5.2
HEAT_SET_INSERT_M3_DEPTH = 5.0
INSERT_BOSS_DIAMETER = 7.2
INSERT_BOSS_HEIGHT = 5.0

# Structural frame
FRAME_RAIL = 14.0
FRAME_THICKNESS = 7.0
FRAME_RIB_HEIGHT = 6.0
FRAME_RIB_WIDTH = 5.0
FRAME_RIB_INSET = 18.0
FRAME_RING_CUTTER_OVERLAP = 2.0
FRAME_EDGE_CHAMFER = 1.0
CORNER_BLOCK_SIZE = 24.0
CORNER_BLOCK_HEIGHT = 28.0
CORNER_BLOCK_EDGE_CHAMFER = 1.0
CORNER_BLOCK_PANEL_HOLE_POINTS = [(0, -6.0), (0, 6.0)]
CORNER_BLOCK_RIB_WIDTH = 5.0
CORNER_BLOCK_RIB_HEIGHT = 3.0

# Metal guide rails for tray load paths
METAL_RAIL_WIDTH = 10.0
METAL_RAIL_THICKNESS = 3.0
METAL_RAIL_HEIGHT = TOWER_HEIGHT - 34.0
METAL_RAIL_X_OFFSET = 84.0
METAL_RAIL_Y_FRONT = -58.0
METAL_RAIL_Y_REAR = 58.0
METAL_RAIL_M3_SPACING = 70.0
METAL_RAIL_FRAME_CLEARANCE = 1.0

# mk0.3 standardized blade module interface
MODULE_TRAY_WIDTH = 170.0
MODULE_TRAY_DEPTH = 176.0
MODULE_TRAY_BASE_HEIGHT = 3.0
MODULE_SIDE_WALL_THICKNESS = WALL_THICKNESS
MODULE_SIDE_WALL_HEIGHT = 12.0
MODULE_FRONT_HANDLE_DEPTH = 4.2
MODULE_REAR_CABLE_CLEARANCE = 36.0
MODULE_RAIL_CLEARANCE = 13.0
MODULE_PRINT_CLEARANCE_Z = 2.0
MODULE_LOCK_SCREW_SIZE = "M3"
MODULE_LOCK_SCREW_CLEARANCE_DIAMETER = SCREW_CLEARANCE_M3
MODULE_LOCK_INSERT_OUTER_DIAMETER = HEAT_SET_INSERT_M3_DIAMETER
MODULE_LOCK_INSERT_DEPTH = HEAT_SET_INSERT_M3_DEPTH
MODULE_LOCK_ANTI_SLIDE_TAB_WIDTH = 18.0
MODULE_LOCK_ANTI_SLIDE_TAB_DEPTH = 4.0
MODULE_LOCK_ANTI_SLIDE_TAB_HEIGHT = 5.0

# Legacy tray names are aliases for the mk0.3 module standard.
TRAY_WIDTH = MODULE_TRAY_WIDTH
TRAY_DEPTH = MODULE_TRAY_DEPTH
TRAY_BASE_THICKNESS = MODULE_TRAY_BASE_HEIGHT
TRAY_SIDE_WALL = MODULE_SIDE_WALL_THICKNESS
TRAY_SIDE_HEIGHT = MODULE_SIDE_WALL_HEIGHT
TRAY_FRONT_LIP = 8.0
TRAY_BACK_CONNECTOR_ZONE = 22.0
TRAY_REAR_SERVICE_CUTOUT_WIDTH = 66.0
TRAY_REAR_SERVICE_CUTOUT_DEPTH = MODULE_REAR_CABLE_CLEARANCE
TRAY_CLEARANCE_Z = MODULE_PRINT_CLEARANCE_Z
TRAY_X = 0.0
TRAY_Y = -4.0
TRAY_MOUNT_HOLE_OFFSET_X = 18.0
TRAY_MOUNT_HOLE_OFFSET_Y = 24.0
TRAY_RAIL_CLEARANCE_WIDTH = MODULE_RAIL_CLEARANCE
TRAY_RAIL_CLEARANCE_DEPTH = 8.0
TRAY_ROD_CORNER_CLEARANCE = 18.0
TRAY_STRUCTURAL_CLEARANCE_HEIGHT = UNIT_HEIGHT * 2.2
TRAY_BACK_STOP_WIDTH_INSET = 24.0
TRAY_BACK_STOP_HEIGHT = 10.0
TRAY_REAR_CONNECTOR_ZONE_X = (-32.0, 32.0)
TRAY_REAR_CONNECTOR_ZONE_WIDTH = 26.0
TRAY_REAR_CONNECTOR_ZONE_DEPTH = 3.0
TRAY_REAR_CONNECTOR_ZONE_HEIGHT = 15.0
TRAY_REAR_CONNECTOR_ZONE_Y_OVERHANG = 0.5
TRAY_BASE_RIB_X = (-45.0, 45.0)
TRAY_BASE_RIB_WIDTH = 4.0
TRAY_BASE_RIB_HEIGHT = 5.0
TRAY_BASE_RIB_Z = 4.0
TRAY_BASE_RIB_LENGTH_INSET = 20.0
TRAY_VENT_ROWS = 3
TRAY_VENT_COLS = 5
TRAY_VENT_AREA_LENGTH = 105.0
TRAY_VENT_AREA_WIDTH = 85.0
TRAY_VENT_SLOT_LENGTH = 18.0
TRAY_VENT_SLOT_WIDTH = 4.0

# Carriage front service interface
CARRIAGE_FRONT_PLATE_THICKNESS = 8.0
CARRIAGE_FRONT_PLATE_HEIGHT = 24.0
CARRIAGE_HANDLE_WIDTH = 64.0
CARRIAGE_HANDLE_HEIGHT = 13.0
CARRIAGE_HANDLE_DEPTH = MODULE_FRONT_HANDLE_DEPTH
CARRIAGE_HANDLE_CORNER_RADIUS = 3.0
CARRIAGE_HANDLE_TOP_BRIDGE = 5.5
CARRIAGE_HANDLE_SIDE_RIB = 8.0
CARRIAGE_HANDLE_FILLET = 1.0
CARRIAGE_LOCK_HOLE_DIAMETER = MODULE_LOCK_SCREW_CLEARANCE_DIAMETER
CARRIAGE_LOCK_BOSS_DIAMETER = 11.0
CARRIAGE_LOCK_BOSS_THICKNESS = MODULE_LOCK_INSERT_DEPTH
CARRIAGE_LOCK_OFFSET_X = 0.0
CARRIAGE_LOCK_OFFSET_Y = 18.0

# Module stack positions from bottom frame top
STACK_START_Z = 18.0
UPS_POWER_TRAY_UNITS = 2.0
EXTERNAL_SSD_BAY_UNITS = 1.0
SSD_EXPANSION_TRAY_UNITS = 1.0
RASPBERRY_PI_TRAY_UNITS = 1.0
MIKROTIK_TRAY_UNITS = 1.5
MINI_PC_TRAY_UNITS = 2.0
TRAY_STACK = [
    ("ups_power_tray", UPS_POWER_TRAY_UNITS),
    ("external_ssd_bay", EXTERNAL_SSD_BAY_UNITS),
    ("ssd_expansion_tray", SSD_EXPANSION_TRAY_UNITS),
    ("raspberry_pi_tray", RASPBERRY_PI_TRAY_UNITS),
    ("mikrotik_tray", MIKROTIK_TRAY_UNITS),
    ("mini_pc_tray", MINI_PC_TRAY_UNITS),
]

# Module placeholder geometry
EXTERNAL_SSD_PLACEHOLDER_WIDTH = 75.0
EXTERNAL_SSD_PLACEHOLDER_DEPTH = 38.0
EXTERNAL_SSD_PLACEHOLDER_HEIGHT = 16.0
SSD_POCKET_LENGTH = 75.0
SSD_POCKET_WIDTH = 38.0
SSD_POCKET_HEIGHT = 16.0
SSD_POCKET_WALL_ALLOWANCE = 6.0
SSD_POCKET_CUTTER_OVERLAP = 2.0
SSD_POCKET_X = -32.0
SSD_POCKET_Y = -22.0
SSD_FRONT_ACCESS_RADIUS = 10.0
SSD_FRONT_ACCESS_DEPTH = 8.0
SSD_CABLE_CUTOUT_WIDTH = 12.0
SSD_CABLE_CUTOUT_LENGTH = 68.0
SSD_CABLE_CUTOUT_HEIGHT = 8.0
SSD_CABLE_CUTOUT_X = 18.0
SSD_CABLE_CUTOUT_Y = 34.0
SSD_CABLE_CUTOUT_Z = 8.0
SSD_STRAP_SLOT_X = (-68.0, 6.0)
SSD_STRAP_SLOT_LENGTH = 34.0
SSD_STRAP_SLOT_WIDTH = 4.0

SSD_EXPANSION_PLACEHOLDER_WIDTH = 110.0
SSD_EXPANSION_PLACEHOLDER_DEPTH = 70.0
SSD_EXPANSION_PLACEHOLDER_HEIGHT = 6.0
SSD_EXPANSION_PLACEHOLDER_LOC = (0.0, -8.0, 6.0)
RASPBERRY_PI_PLACEHOLDER_WIDTH = 86.0
RASPBERRY_PI_PLACEHOLDER_DEPTH = 57.0
RASPBERRY_PI_PLACEHOLDER_HEIGHT = 8.0
RASPBERRY_PI_PLACEHOLDER = (
    RASPBERRY_PI_PLACEHOLDER_WIDTH,
    RASPBERRY_PI_PLACEHOLDER_DEPTH,
    RASPBERRY_PI_PLACEHOLDER_HEIGHT,
)
MODULE_BOARD_MARKER_HEIGHT = 2.0
MODULE_DEVICE_MARKER_HEIGHT = 3.0
RASPBERRY_PI_PLACEHOLDER_LOC = (-24.0, -14.0, 6.0)
RPI_FAN_ZONE_WIDTH = 44.0
RPI_FAN_ZONE_DEPTH = 44.0
RPI_FAN_ZONE_HEIGHT = 2.0
RPI_FAN_ZONE_LOC = (48.0, 30.0, 7.0)

MIKROTIK_PLACEHOLDER_WIDTH = 120.0
MIKROTIK_PLACEHOLDER_DEPTH = 95.0
MIKROTIK_PLACEHOLDER_HEIGHT = 14.0
MIKROTIK_PLACEHOLDER = (
    MIKROTIK_PLACEHOLDER_WIDTH,
    MIKROTIK_PLACEHOLDER_DEPTH,
    MIKROTIK_PLACEHOLDER_HEIGHT,
)  # TODO: measure bare hAP ax2 board.
MIKROTIK_PLACEHOLDER_LOC = (0.0, -8.0, 6.0)
MIKROTIK_ETHERNET_WINDOW_WIDTH = 80.0
MIKROTIK_ETHERNET_WINDOW_DEPTH = 8.0
MIKROTIK_ETHERNET_WINDOW_HEIGHT = 14.0
MIKROTIK_ETHERNET_WINDOW_REAR_INSET = 2.0
MIKROTIK_ETHERNET_WINDOW_Z = 12.0

MINI_PC_PLACEHOLDER_WIDTH = 145.0
MINI_PC_PLACEHOLDER_DEPTH = 130.0
MINI_PC_PLACEHOLDER_HEIGHT = 28.0
MINI_PC_PLACEHOLDER = (
    MINI_PC_PLACEHOLDER_WIDTH,
    MINI_PC_PLACEHOLDER_DEPTH,
    MINI_PC_PLACEHOLDER_HEIGHT,
)  # TODO: measure Ryzen 5 PRO 4650U unit.
MINI_PC_PLACEHOLDER_LOC = (0.0, -8.0, 7.0)
MINI_PC_HEAT_ZONE_WIDTH = 76.0
MINI_PC_HEAT_ZONE_DEPTH = 54.0
MINI_PC_HEAT_ZONE_HEIGHT = 4.0
MINI_PC_HEAT_ZONE_LOC = (25.0, 10.0, 11.0)
MINI_PC_POWER_WINDOW_WIDTH = 18.0
MINI_PC_POWER_WINDOW_DEPTH = 8.0
MINI_PC_POWER_WINDOW_HEIGHT = 14.0
MINI_PC_POWER_WINDOW_X = -54.0
MINI_PC_POWER_WINDOW_REAR_INSET = 2.0
MINI_PC_POWER_WINDOW_Z = 13.0

UPS_PLACEHOLDER_WIDTH = 125.0
UPS_PLACEHOLDER_DEPTH = 55.0
UPS_PLACEHOLDER_HEIGHT = 32.0
UPS_PLACEHOLDER_LOC = (-38.0, -25.0, 6.0)
BATTERY_PACK_PLACEHOLDER = (UPS_PLACEHOLDER_WIDTH, UPS_PLACEHOLDER_DEPTH, UPS_PLACEHOLDER_HEIGHT)
BOARD_PLACEHOLDER_HEIGHT = 4.0
UPS_ZONE_MARKER_HEIGHT = 3.0
UPS_ZONE_MARKER_Z = 6.0
UPS_COMPONENT_ZONES = [
    (-38.0, -25.0, BATTERY_PACK_PLACEHOLDER[0], BATTERY_PACK_PLACEHOLDER[1], "battery"),
    (48.0, 24.0, 54.0, 38.0, "ups_board"),
    (48.0, -26.0, 42.0, 26.0, "bms"),
    (-50.0, 54.0, 48.0, 24.0, "fuse_block"),
    (-6.0, 58.0, 38.0, 24.0, "dc_dc"),
    (44.0, 62.0, 58.0, 18.0, "terminal_blocks"),
]
UPS_EXTRA_MOUNT_X = (-72.0, 72.0)
UPS_EXTRA_MOUNT_Y = (-58.0, 58.0)
UPS_STRAP_SLOT_X = (-64.0, -12.0, 36.0, 70.0)
UPS_STRAP_SLOT_LENGTH = 12.0
UPS_STRAP_SLOT_WIDTH = 3.0

# Side service panels
PANEL_THICKNESS = 3.0
SIDE_PANEL_THICKNESS = PANEL_THICKNESS
SIDE_PANEL_HEIGHT = TOWER_HEIGHT - 18.0
SIDE_PANEL_FRAME_WIDTH = 10.0
SIDE_PANEL_RIB_WIDTH = 5.0
SIDE_PANEL_RIB_HEIGHT = 2.2
SIDE_PANEL_CLEARANCE = 6.0
SIDE_PANEL_MOUNT_HOLE_DIAMETER = M3_CLEARANCE
SIDE_PANEL_MOUNT_BOSS_DIAMETER = 10.0
SIDE_PANEL_VENT_SLOT_WIDTH = 4.0
SIDE_PANEL_VENT_SLOT_LENGTH = 26.0
SIDE_PANEL_VENT_SLOT_SPACING = 15.0
SIDE_PANEL_CORNER_RADIUS = 1.0
SIDE_PANEL_MINIPC_DUCT_CLEARANCE = 8.0
MINIPC_DUCT_ZONE_HEIGHT = UNIT_HEIGHT * 2.0 - 8.0
MINIPC_DUCT_ZONE_OFFSET_Z = STACK_START_Z + UNIT_HEIGHT * 6.5

# Cooling
FAN_SIZE = 120.0
FAN_HOLE_SPACING = 105.0
FAN_SCREW_DIAMETER = 4.4
FAN_PANEL_THICKNESS = 4.0
FAN_GRILLE_THICKNESS = FAN_PANEL_THICKNESS
FAN_PANEL_EDGE_CHAMFER = 0.6
FAN_GRILLE_BAR_WIDTH = 3.0
FAN_GRILLE_BAR_LENGTH_INSET = 18.0
FAN_GRILLE_BAR_X = (-48.0, -24.0, 0.0, 24.0, 48.0)
FAN_GRILLE_BAR_Y = (-48.0, -24.0, 0.0, 24.0, 48.0)
FILTER_RAIL_HEIGHT = 3.0
FILTER_RAIL_WIDTH = 3.0
FILTER_RAIL_OFFSET = 8.0
FILTER_RAIL_LENGTH_ALLOWANCE = 18.0
DUCT_WIDTH = 58.0
DUCT_DEPTH = 134.0
DUCT_HEIGHT = UNIT_HEIGHT * 2.0 - 8.0
DUCT_WALL = 2.0
DUCT_CUTTER_OVERLAP = 2.0
DUCT_TAB_WIDTH = 14.0
DUCT_TAB_DEPTH = 20.0
DUCT_TAB_HEIGHT = 4.0
DUCT_TAB_OFFSET_X = 8.0
DUCT_TAB_OFFSET_Y = 16.0
DUCT_TAB_OFFSET_Z = 8.0
DUCT_EDGE_CHAMFER = 0.8

# Rear service spine and low-voltage power bus
REAR_SPINE_WIDTH = 52.0
REAR_SPINE_DEPTH = 30.0
REAR_SPINE_HEIGHT = TOWER_HEIGHT - 24.0
REAR_SPINE_WALL_THICKNESS = WALL_THICKNESS
REAR_SPINE_CABLE_SLOT_WIDTH = 34.0
REAR_SPINE_CABLE_SLOT_HEIGHT = 20.0
REAR_SPINE_TIE_SLOT_WIDTH = 4.0
REAR_SPINE_TIE_SLOT_HEIGHT = 18.0
REAR_SPINE_POWER_ZONE_WIDTH = 22.0
REAR_SPINE_SIGNAL_ZONE_WIDTH = 18.0
REAR_SPINE_COVER_RAIL_WIDTH = 3.0
REAR_SPINE_COVER_RAIL_DEPTH = 3.0
REAR_SPINE_CHANNEL_SIDE_MARGIN = 2 * REAR_SPINE_WALL_THICKNESS
REAR_SPINE_CHANNEL_DEPTH_OVERLAP = 2.0
REAR_SPINE_CHANNEL_HEIGHT_MARGIN = 22.0
REAR_SPINE_CHANNEL_Y_OFFSET = -2.0
REAR_SPINE_WINDOW_WIDTH = REAR_SPINE_CABLE_SLOT_WIDTH
REAR_SPINE_WINDOW_DEPTH = REAR_SPINE_DEPTH + 2.0
REAR_SPINE_WINDOW_HEIGHT = REAR_SPINE_CABLE_SLOT_HEIGHT
REAR_SPINE_WINDOW_Z = (-124.0, -71.5, -19.0, 33.5, 77.25, 138.5)
REAR_SPINE_MOUNT_Z = (-120.0, 0.0, 120.0)
REAR_SPINE_TIE_SLOT_X = (-15.0, 15.0)
REAR_SPINE_TIE_SLOT_Z = (-110.0, -55.0, 0.0, 55.0, 110.0)

POWER_BUS_WIDTH = 34.0
POWER_BUS_HEIGHT = TOWER_HEIGHT - 46.0
POWER_BUS_THICKNESS = 3.0
POWER_BUS_PAD_WIDTH = 22.0
POWER_BUS_PAD_DEPTH = 4.0
POWER_BUS_PAD_HEIGHT = 22.0
POWER_BUS_PAD_Y = -3.5
POWER_BUS_PAD_SCREW_OFFSET_X = 7.0
POWER_BUS_CONNECTOR_CUT_DEPTH = 5.0
POWER_BUS_RAIL_LABELS = [
    ("19V", 70.0),
    ("12V", 25.0),
    ("5V", -20.0),
    ("GND", -65.0),
]
POWER_BUS_CONNECTOR_ZONES = [
    (0.0, 112.0, 24.0, 14.0, "xt30_19v"),
    (0.0, 48.0, 20.0, 10.0, "microfit_12v"),
    (0.0, -48.0, 18.0, 8.0, "usb_c_5v"),
    (0.0, -112.0, 24.0, 10.0, "cable_tie"),
]

# Assembly placement
SIDE_PANEL_ASSEMBLY_ROTATION_DEG = 90.0
POWER_BUS_PANEL_OFFSET_Y = 10.0
BOTTOM_FAN_PANEL_Z = -2.0
TOP_FAN_PANEL_Z_OFFSET = 2.0
MINI_PC_DUCT_ASSEMBLY_X = 48.0
MINI_PC_DUCT_ASSEMBLY_Y = 6.0

# Export settings
EXPORTS_ROOT = "exports"
STEP_DIR = "exports/step"
STL_DIR = "exports/stl"
STL_TOLERANCE = 0.15
STL_ANGULAR_TOLERANCE = 0.15
