"""Parametric dimensions for Homelab Modular Tower v1.

All dimensions are in millimetres. The first version intentionally uses
placeholder component sizes where real boards and connectors still need
caliper measurements.
"""

PROJECT_NAME = "Homelab Modular Tower v1"
CURRENT_REVISION = "mk0.1"

# Envelope
TOWER_WIDTH = 190.0
TOWER_DEPTH = 190.0
OUTER_WIDTH = 190.0
OUTER_DEPTH = 190.0
UNIT_HEIGHT = 35.0
TOTAL_UNITS = 8.5
TOWER_HEIGHT = TOTAL_UNITS * UNIT_HEIGHT + 24.0

# Frame and rods
FRAME_RAIL = 14.0
FRAME_THICKNESS = 8.0
WALL_THICKNESS = 3.0
CORNER_BLOCK_SIZE = 24.0
CORNER_BLOCK_HEIGHT = 28.0
ROD_DIAMETER = 5.0
ROD_CLEARANCE = 5.6
ROD_CENTER_OFFSET = 12.0
ROD_OFFSET = ROD_CENTER_OFFSET
ROD_LENGTH = TOWER_HEIGHT + 24.0
M5_WASHER_DIAMETER = 12.0
M5_WASHER_SEAT_DEPTH = 1.8
M5_NUT_FLAT_DIAMETER = 9.4
M5_NUT_SEAT_DEPTH = 4.2
M3_CLEARANCE = 3.4
M4_CLEARANCE = 4.4
INSERT_BOSS_DIAMETER = 7.2
INSERT_BOSS_HEIGHT = 5.0

# Metal guide rails for tray load paths
METAL_RAIL_WIDTH = 10.0
METAL_RAIL_THICKNESS = 3.0
METAL_RAIL_HEIGHT = TOWER_HEIGHT - 34.0
METAL_RAIL_X_OFFSET = 84.0
METAL_RAIL_Y_FRONT = -58.0
METAL_RAIL_Y_REAR = 58.0
METAL_RAIL_M3_SPACING = 70.0
TRAY_RAIL_CLEARANCE_WIDTH = 13.0
TRAY_RAIL_CLEARANCE_DEPTH = 8.0
TRAY_ROD_CORNER_CLEARANCE = 18.0

# Trays
TRAY_WIDTH = 170.0
TRAY_DEPTH = 176.0
TRAY_BASE_THICKNESS = 3.0
TRAY_SIDE_WALL = 3.0
TRAY_SIDE_HEIGHT = 12.0
TRAY_FRONT_LIP = 8.0
TRAY_BACK_CONNECTOR_ZONE = 22.0
TRAY_REAR_SERVICE_CUTOUT_WIDTH = 48.0
TRAY_REAR_SERVICE_CUTOUT_DEPTH = 28.0
TRAY_CLEARANCE_Z = 2.0
TRAY_X = 0.0
TRAY_Y = -4.0

# Stack positions from bottom frame top
STACK_START_Z = 18.0
TRAY_STACK = [
    ("ups_power_tray", 2.0),
    ("external_ssd_bay", 1.0),
    ("ssd_expansion_tray", 1.0),
    ("raspberry_pi_tray", 1.0),
    ("mikrotik_tray", 1.5),
    ("mini_pc_tray", 2.0),
]

# Panels and rear service area
PANEL_THICKNESS = 3.0
SIDE_PANEL_HEIGHT = TOWER_HEIGHT - 18.0
REAR_SPINE_WIDTH = 34.0
REAR_SPINE_DEPTH = 18.0
REAR_SPINE_HEIGHT = TOWER_HEIGHT - 24.0
POWER_BUS_WIDTH = 30.0
POWER_BUS_HEIGHT = TOWER_HEIGHT - 46.0
POWER_BUS_THICKNESS = 3.0

# Fans and airflow
FAN_SIZE = 120.0
FAN_HOLE_SPACING = 105.0
FAN_SCREW_DIAMETER = 4.4
FAN_PANEL_THICKNESS = 4.0
FILTER_RAIL_HEIGHT = 3.0
DUCT_WIDTH = 58.0
DUCT_DEPTH = 134.0
DUCT_HEIGHT = UNIT_HEIGHT * 2.0 - 8.0
DUCT_WALL = 2.0

# Placeholder devices
SSD_POCKET_LENGTH = 75.0
SSD_POCKET_WIDTH = 38.0
SSD_POCKET_HEIGHT = 16.0
RASPBERRY_PI_PLACEHOLDER = (86.0, 57.0, 8.0)
MIKROTIK_PLACEHOLDER = (120.0, 95.0, 14.0)  # TODO: measure bare hAP ax2 board.
MINI_PC_PLACEHOLDER = (145.0, 130.0, 28.0)  # TODO: measure Ryzen 5 PRO 4650U unit.
BATTERY_PACK_PLACEHOLDER = (125.0, 55.0, 32.0)  # TODO: select LiFePO4 pack.
BOARD_PLACEHOLDER_HEIGHT = 4.0

# Export
EXPORTS_ROOT = "exports"
STEP_DIR = "exports/step"
STL_DIR = "exports/stl"
STL_TOLERANCE = 0.15
STL_ANGULAR_TOLERANCE = 0.15
